### PR TITLE
Add JRuby's iconv ext.

### PR DESCRIPTION
**Pull request by hsbt**
I picked https://github.com/ruby/iconv/pull/7 and fixed conflict.

### CODE REVIEW

**Comment by hsbt** [comment]
@headius I could compile `lib/iconv/iconv_jruby.jar` But https://github.com/ruby/iconv/pull/19/files#diff-2c91fc8457d0f1d323ce0701563dca186310712c52eb8c12998550c719e5538bR5 is not working yet.

```
NameError: missing class name (`org.jruby.ext.iconv.IConvLibrary')
                                                              method_missing at org/jruby/javasupport/JavaPackage.java:252
                                                                      <main> at /Users/hsbt/Documents/github.com/ruby/iconv/lib/iconv.rb:5
                                                                     require at org/jruby/RubyKernel.java:974
                                                                     require at /Users/hsbt/.local/share/rbenv/versions/jruby-9.2.20.1/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83
                                                                      <main> at /Users/hsbt/Documents/github.com/ruby/iconv/test/utils.rb:1
                                                                     require at org/jruby/RubyKernel.java:974
                                                                     require at /Users/hsbt/.local/share/rbenv/versions/jruby-9.2.20.1/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83
                                                                      <main> at /Users/hsbt/Documents/github.com/ruby/iconv/test/test_basic.rb:3
                                                                     require at org/jruby/RubyKernel.java:974
                                                                     require at /Users/hsbt/.local/share/rbenv/versions/jruby-9.2.20.1/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83
  /Users/hsbt/.local/share/gem/gems/rake-13.0.6/lib/rake/rake_test_loader.rb at /Users/hsbt/.local/share/gem/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21
                                                                      select at org/jruby/RubyArray.java:2668
                                                                      <main> at /Users/hsbt/.local/share/gem/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6
rake aborted!
```

Can you look this?

**Comment by hsbt** [comment]
@headius /cc @enebo Do you still interested this integration?

**Comment by headius** [comment]
Well that is a good question. We are not sure how important this library is
anymore. We have what we have, but do people still use iconv much?

**Comment by headius** [comment]
@hsbt Is iconv still being shipped with CRuby?

**Comment by hsbt** [comment]
@headius No. iconv is already extracted from CRuby. In Japan, mostly use-cases are enough with NKF conversion. But some of encoding or case need iconv.

I have no strong opinion about this integration. But If you hope to ship JRuby code with iconv gem, I support it.

**Comment by headius** [comment]
@hsbt I think at this point it is very low priority. I think we should close this and wait to see if someone eventually needs it.

Thank you for your help!

**Comment by hsbt** [comment]
I see. Thanks for your time.

**Pull request closed without merging**
